version: '2.1'
services:
  smtpd:
    image: "frawi/opensmtpd"
    restart: always
    hostname: mail
    domainname: kryptolyse.org
    ports:
        - "25:25"
        - "587:587"
    expose:
      - "10028"
    volumes:
      - "/etc/mail/smtpd:/etc/smtpd"
      - "/etc/letsencrypt:/etc/ssl/server"
      - "/var/spool/smtpd:/var/spool/smtpd"
    command: /usr/sbin/smtpd -d -f /etc/smtpd/smtpd.conf
    networks:
      mail_net:
        ipv4_address: 172.16.1.2
        ipv6_address: fdc5:04a5:5cf1:d772::2
  dovecot:
    image: "frawi/dovecot"
    restart: always
    ports:
        - "143:143"
        - "4190:4190"
    expose:
      - "2525"
    volumes:
      - "/etc/mail/dovecot:/etc/dovecot"
      - "/srv/mail:/home"
      - "/etc/letsencrypt:/etc/ssl/server"
    networks:
      mail_net:
        ipv4_address: 172.16.1.3
        ipv6_address: fdc5:04a5:5cf1:d772::3
  rspamd:
    image: "frawi/rspamd"
    restart: always
    ports:
      - "127.0.0.1:11334:11334"
    expose:
      - "11333"
    volumes:
      - "/etc/mail/rspamd:/etc/rspamd/local.d"
      - "/var/lib/rspamd:/var/lib/rspamd"
    networks:
      mail_net:
        ipv4_address: 172.16.1.4
        ipv6_address: fdc5:04a5:5cf1:d772::4
  dkimproxy:
    image: "frawi/dkimproxy"
    restart: always
    expose:
      - "10027"
    volumes:
      - "/etc/mail/dkimproxy:/etc/dkimproxy"
    networks:
      mail_net:
        ipv4_address: 172.16.1.5
        ipv6_address: fdc5:04a5:5cf1:d772::5
networks:
  mail_net:
    driver: bridge
    enable_ipv6: true
    driver_opts:
      com.docker.network.bridge.name: "br-mail"
    ipam:
      driver: default
      config:
        - subnet: 172.16.1.0/24
        - subnet: fdc5:04a5:5cf1:d772::/64
